name: Release

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      is_pre: ${{ steps.check.outputs.is_pre }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: check
        run: |
          # Check that the ".changeset/pre.json" file exists, and also check
          # that the pre.json file has a property called "mode" with value
          # "pre" using the "jq" CLI tool.
          if [ -f ".changeset/pre.json" ] && [ "$(jq -r '.mode' .changeset/pre.json)" = "pre" ]; then
            echo "is_pre=true" >> $GITHUB_OUTPUT
          else
            echo "is_pre=false" >> $GITHUB_OUTPUT
          fi

  release:
    runs-on: ubuntu-latest
    needs: [check-release]
    if: ${{ github.ref == 'refs/heads/main' || needs.check-release.outputs.is_pre == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-and-build
      - uses: changesets/action@v1
        id: changesets
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: test # disable npm access checks; they don't work in CI
