name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: What kind of release?
        required: true
        options:
          - patch
          - minor
          - major
      npm_tag:
        type: choice
        description: What npm tag do you want to target?
        default: latest
        options:
          - latest
          - beta

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  checks:
    uses: ./.github/workflows/pr.yml

  npm:
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-and-build
      - run: |
          git config user.name "botbot"
          git config user.email "<>"
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          cat .npmrc
          yarn run release ${{ github.event.inputs.type }} --tag=${{ github.event.inputs.npm_tag }} --any-branch --no-tests
        env:
          NODE_ENV: test # disable npm access checks; they don't work in CI

